services:
  torch-nginx:
      restart: unless-stopped
      image: nginxinc/nginx-unprivileged:1.25.5-alpine
      ports:
        - ${TORCH_NGINX_PORT:-127.0.0.1:80}:8080
      volumes:
        - ./torch.nginx.conf:/etc/nginx/nginx.conf
        - triangle-torch-data-store:/app/output
  torch:
    restart: unless-stopped
    image: ghcr.io/medizininformatik-initiative/torch:develop
    ports:
      - ${TORCH_PORT:-127.0.0.1:8086}:8080
    environment:
      TORCH_FHIR_URL: ${TORCH_FHIR_URL:-http://torch-data-store:8080/fhir}
      TORCH_FLARE_URL: ${TORCH_FLARE_URL:-http://torch-flare:8080}
      TORCH_MAPPING_CONSENT: /app/Mappings/consent-mappings_fhir.json
      TORCH_MAPPING_CONSENT_TO_PROFILE: /app/Mappings/profile_to_consent.json
      TORCH_PROFILE_DIR: /app/structureDefinitions
      TORCH_RESULTS_PERSISTENCE: ${TORCH_RESULTS_PERSISTENCE:-PT12H30M5S}
      LOG_LEVEL: ${TORCH_LOG_LEVEL:-debug}
      NGINX_FILELOCATION: ${TORCH_NGINX_FILELOCATION:-http://localhost:80}
      TORCH_BATCHSIZE: ${TORCH_BATCHSIZE:-100}
      TORCH_MAXCONCURRENCY: ${TORCH_MAXCONCURRENCY:-4}
      TORCH_USE_CQL: ${TORCH_USE_CQL:-true}
    volumes:
      - "triangle-torch-data-store:/app/output"
      - ../auth:/app/certs
    extra_hosts:
      - "auth.localhost:host-gateway"

volumes:
  triangle-torch-data-store: