services:
  torch-nginx:
      restart: unless-stopped
      image: nginxinc/nginx-unprivileged:1.27-alpine
      ports:
        - ${TORCH_NGINX_PORT:-127.0.0.1:80}:8080
      volumes:
        - ./torch.nginx.conf:/etc/nginx/nginx.conf
        - triangle-torch-data-store:/app/output
  torch:
    restart: unless-stopped
    image: ghcr.io/medizininformatik-initiative/torch:1.0.0-alpha.3
    ports:
      - ${TORCH_PORT:-127.0.0.1:8086}:8080
    environment:
      JAVA_TOOL_OPTIONS: ${TORCH_JVM_ARGS:--Xmx4g}
      TORCH_FHIR_URL: ${TORCH_FHIR_URL:-http://torch-data-store:8080/fhir}
      TORCH_FLARE_URL: ${TORCH_FLARE_URL:-http://torch-flare:8080}
      TORCH_MAPPING_CONSENT: /app/mappings/consent-mappings_fhir.json
      TORCH_MAPPING_CONSENT_TO_PROFILE: /app/mappings/profile_to_consent.json
      TORCH_PROFILE_DIR: /app/structureDefinitions
      TORCH_RESULTS_PERSISTENCE: ${TORCH_RESULTS_PERSISTENCE:-PT12H30M5S}
      LOG_LEVEL: ${TORCH_LOG_LEVEL:-INFO}
      NGINX_FILELOCATION: ${TORCH_NGINX_FILELOCATION:-http://localhost:80}
      TORCH_BATCHSIZE: ${TORCH_BATCHSIZE:-100}
      TORCH_MAXCONCURRENCY: ${TORCH_MAXCONCURRENCY:-4}
      TORCH_USE_CQL: ${TORCH_USE_CQL:-true}
      TORCH_FHIR_USER: ${TORCH_FHIR_USER:-""}
      TORCH_FHIR_PASSWORD: ${TORCH_FHIR_PASSWORD:-""}
      TORCH_FHIR_OAUTH_ISSUER_URI: ${TORCH_FHIR_OAUTH_ISSUER_URI:-https://auth.localhost:444/realms/blaze}
      TORCH_FHIR_OAUTH_CLIENT_ID: ${TORCH_FHIR_OAUTH_CLIENT_ID:-account}
      TORCH_FHIR_OAUTH_CLIENT_SECRET: ${TORCH_FHIR_OAUTH_CLIENT_SECRET:-insecure}
    volumes:
      - "triangle-torch-data-store:/app/output"
      - ../auth:/app/certs
    extra_hosts:
      - "auth.localhost:host-gateway"

volumes:
  triangle-torch-data-store:
