version: '3.7'

services:

  # ---- Proxy -----------------------------------------------------------------
  dsf-zars-fhir-proxy:
    image: nginx:1.25.1
    restart: on-failure
    ports:
    - "127.0.0.1:445:443"
    secrets:
    - proxy_certificate_and_int_cas.pem
    - proxy_certificate_private_key.pem
    - proxy_trusted_client_cas.pem
    volumes:
    - type: bind
      source: ./proxy/nginx.conf
      target: /etc/nginx/nginx.conf
      read_only: true
    environment:
      TZ: Europe/Berlin
    depends_on:
      - dsf-zars-fhir-app

  # ---- FHIR ------------------------------------------------------------------
  dsf-zars-fhir-app:
    image: ghcr.io/datasharingframework/fhir:1.5.0
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "./healthcheck.sh" ]
      interval: 10s
      timeout: 15s
      retries: 5
    ports:
    - "127.0.0.1:11345:8080"
    volumes:
      - type: bind
        source: ${FEASIBILITY_DSF_FHIR_LOG_FOLDER_PATH:-./log}
        target: /opt/fhir/log
    secrets:
      - db_liquibase.password
      - db_fhir_zars_user.password
      - db_fhir_zars_user_permanent_delete.password
      - app_client_trust_certificates.pem
      - app_zars_client_certificate.pem
      - app_zars_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    environment:
      DEV_DSF_SERVER_AUTH_TRUST_CLIENT_CERTIFICATE_CAS: /run/secrets/app_client_trust_certificates.pem
      DEV_DSF_FHIR_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      DEV_DSF_FHIR_DB_USER_PASSWORD_FILE: /run/secrets/db_fhir_zars_user.password
      DEV_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE: /run/secrets/db_fhir_zars_user_permanent_delete.password
      DEV_DSF_FHIR_CLIENT_TRUST_SERVER_CERTIFICATE_CAS: /run/secrets/app_client_trust_certificates.pem
      DEV_DSF_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_zars_client_certificate.pem
      DEV_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_zars_client_certificate_private_key.pem
      DEV_DSF_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      DEV_DSF_FHIR_DB_URL: jdbc:postgresql://dsf-zars-fhir-db/fhir
      DEV_DSF_FHIR_SERVER_BASE_URL: ${FEASIBILITY_DSF_FHIR_SERVER_BASE_URL}
      DEV_DSF_FHIR_SERVER_ORGANIZATION_IDENTIFIER_VALUE: ${FEASIBILITY_DSF_FHIR_ORGANIZATION_IDENTIFIER}
      DEV_DSF_FHIR_SERVER_ORGANIZATION_THUMBPRINT: ${FEASIBILITY_DSF_FHIR_ORGANIZATION_THUMBPRINT}
      DEV_DSF_FHIR_SERVER_ROLECONFIG: |
        - webbrowser_test_user:
            thumbprint: ${FEASIBILITY_DSF_FHIR_BACKEND_THUMBPRINT}
            token-role: admin
            dsf-role:
              - CREATE
              - READ
              - UPDATE
              - DELETE
              - SEARCH
              - HISTORY
              - PERMANENT_DELETE
              - WEBSOCKET
            practitioner-role:
              - http://dsf.dev/fhir/CodeSystem/practitioner-role|DSF_ADMIN
      EXTRA_JVM_ARGS: ${FEASIBILITY_DSF_ZARS_FHIR_APP_JVM_ARGS}
      TZ: Europe/Berlin
      #CORS_ORIGINS: "http://zars-feasibility-gui-backend"
      # ORGANIZATION_TYPE: "MeDIC"  - needs to be put into the fhir resource organisation
    depends_on:
    - dsf-zars-fhir-db

  dsf-zars-fhir-db:
    image: postgres:15
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d fhir" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: fhir
    volumes:
    - type: volume
      source: dsf-zars-fhir-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

  # ---- BPE -------------------------------------------------------------------
  dsf-zars-bpe-app:
    image: ghcr.io/datasharingframework/bpe:1.5.0
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "./healthcheck.sh" ]
      interval: 10s
      timeout: 15s
      retries: 5
    volumes:
      - type: bind
        source: ${FEASIBILITY_DSF_BPE_PROCESS_PLUGINS_DIRECTORY_PATH:-./process}
        target: /opt/bpe/process
        read_only: true
      - type: bind
        source: ${FEASIBILITY_DSF_BPE_LOG_FOLDER_PATH:-./log}
        target: /opt/bpe/log
      - type: bind
        source: ${FEASIBILITY_DSF_BPE_LAST_EVENT_FOLDER_PATH:-./bpe/app/last_event}
        target: /opt/bpe/last_event
      - type: bind
        source: ${FEASIBILITY_DSF_BPE_CACHE_FOLDER_PATH:-./bpe/cache}
        target: /opt/bpe/cache
    secrets:
      - db_liquibase.password
      - db_zars_bpe_user.password
      - db_zars_bpe_user_camunda.password
      - app_client_trust_certificates.pem
      - app_zars_client_certificate.pem
      - app_zars_client_certificate_private_key.pem
      - app_client_certificate_private_key.pem.password
    environment:
      DEV_DSF_SERVER_AUTH_TRUST_CLIENT_CERTIFICATE_CAS: /run/secrets/app_client_trust_certificates.pem
      DEV_DSF_BPE_DB_LIQUIBASE_PASSWORD_FILE: /run/secrets/db_liquibase.password
      DEV_DSF_BPE_DB_USER_PASSWORD_FILE: /run/secrets/db_zars_bpe_user.password
      DEV_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE: /run/secrets/db_zars_bpe_user_camunda.password
      DEV_DSF_BPE_FHIR_CLIENT_TRUST_SERVER_CERTIFICATE_CAS: /run/secrets/app_client_trust_certificates.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE: /run/secrets/app_zars_client_certificate.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY: /run/secrets/app_zars_client_certificate_private_key.pem
      DEV_DSF_BPE_FHIR_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE: /run/secrets/app_client_certificate_private_key.pem.password
      DEV_DSF_BPE_DB_URL: jdbc:postgresql://dsf-zars-bpe-db/bpe
      DEV_DSF_BPE_DB_USER_GROUP: zars_bpe_users
      DEV_DSF_BPE_DB_USER_USERNAME: zars_bpe_server_user
      DEV_DSF_BPE_DB_USER_CAMUNDA_GROUP: zars_camunda_users
      DEV_DSF_BPE_DB_USER_CAMUNDA_USERNAME: zars_camunda_server_user
      DEV_DSF_BPE_FHIR_SERVER_BASE_URL: ${FEASIBILITY_DSF_FHIR_SERVER_BASE_URL}
      DEV_DSF_BPE_PROCESS_EXCLUDED: ${FEASIBILITY_DSF_BPE_PROCESS_EXCLUDED}
      EXTRA_JVM_ARGS: ${FEASIBILITY_DSF_BPE_APP_JVM_ARGS}
      TZ: "Europe/Berlin"
      # WEBSOCKET_URL: "wss://dsf-zars-fhir-proxy/fhir/ws"
    depends_on:
    - dsf-zars-bpe-db
    - dsf-zars-fhir-proxy

  dsf-zars-bpe-db:
    image: postgres:15
    restart: on-failure
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U liquibase_user -d bpe" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_liquibase.password
      POSTGRES_USER: liquibase_user
      POSTGRES_DB: bpe
    volumes:
    - type: volume
      source: dsf-zars-bpe-db-data
      target: /var/lib/postgresql/data
    secrets:
    - db_liquibase.password

secrets:
  # ---- Common Secrets ---------------------------------------------------------
  app_client_trust_certificates.pem:
    file: ${FEASIBILITY_DSF_CLIENT_TRUST_CERTIFICATES_FILE:-../../secrets/app_client_trust_certificates.pem}
  app_client_certificate_private_key.pem.password:
    file: ${FEASIBILITY_DSF_CLIENT_CERTIFICATE_PRIVATE_KEY_PASSWORD_FILE:-../../secrets/app_client_certificate_private_key.pem.password}
  app_zars_client_certificate.pem:
    file: ${FEASIBILITY_DSF_CLIENT_CERTIFICATE_FILE:-../../secrets/app_zars_client_certificate.pem}
  app_zars_client_certificate_private_key.pem:
    file: ${FEASIBILITY_DSF_CLIENT_CERTIFICATE_PRIVATE_KEY_FILE:-../../secrets/app_zars_client_certificate_private_key.pem}
  db_liquibase.password:
    file: ${FEASIBILITY_DSF_DB_LIQUIBASE_PASSWORD_FILE:-../../secrets/db_liquibase.password}

  # ---- Proxy Secrets -----------------------------------------------------------
  proxy_certificate_and_int_cas.pem:
    file: ${FEASIBILITY_DSF_PROXY_CERTIFICATE_AND_INTERMEDIATE_CAS_FILE:-../../secrets/proxy_certificate_and_int_cas.pem}
  proxy_certificate_private_key.pem:
    file: ${FEASIBILITY_DSF_PROXY_CERTIFICATE_PRIVATE_KEY_FILE:-../../secrets/proxy_certificate_private_key.pem}
  proxy_trusted_client_cas.pem:
    file: ${FEASIBILITY_DSF_PROXY_TRUSTED_CLIENT_CAS_FILE:-../../secrets/proxy_trusted_client_cas.pem}

  # ---- FHIR Secrets -----------------------------------------------------------
  db_fhir_zars_user.password:
    file: ${FEASIBILITY_DSF_FHIR_DB_USER_PASSWORD_FILE:-../../secrets/db_fhir_zars_user.password}
  db_fhir_zars_user_permanent_delete.password:
    file: ${FEASIBILITY_DSF_FHIR_DB_USER_PERMANENT_DELETE_PASSWORD_FILE:-../../secrets/db_fhir_zars_user_permanent_delete.password}

  # ---- BPE Secrets ------------------------------------------------------------
  db_zars_bpe_user.password:
    file: ${FEASIBILITY_DSF_BPE_DB_USER_PASSWORD_FILE:-../../secrets/db_zars_bpe_user.password}
  db_zars_bpe_user_camunda.password:
    file: ${FEASIBILITY_DSF_BPE_DB_USER_CAMUNDA_PASSWORD_FILE:-../../secrets/db_zars_bpe_user_camunda.password}

volumes:
  dsf-zars-fhir-db-data:
    name: "dsf-zars-fhir-db-data"
  dsf-zars-bpe-db-data:
    name: "dsf-zars-bpe-db-data"
