services:
  dataportal-nginx:
    restart: unless-stopped
    image: nginxinc/nginx-unprivileged:1.23-alpine
    environment:
      BACKEND_HOSTNAME: ${BACKEND_HOSTNAME:-api.datenportal.localhost}
      GUI_HOSTNAME:    ${GUI_HOSTNAME:-datenportal.localhost} 
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME:-auth.datenportal.localhost}
    ports:
      - 443:8443
    volumes:
      - ${PROXY_CERTIFICATE_PATH:-../auth/cert.pem}:/etc/nginx/conf.d/cert.pem
      - ${PROXY_CERTIFICATE_KEY_PATH:-../auth/key.pem}:/etc/nginx/conf.d/key.pem
      - ${PROXY_NGINX_CONFIG_PATH:-./nginx.conf}:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/templates


