# Comment one of the FEASIBILITY_PORTAL_PROXY_NGINX_CONFIG depending if it is used 'subdomains.nginx.conf' or 'context-paths.nginx.conf'
services:
  dataportal-nginx:
    restart: unless-stopped
    image: nginxinc/nginx-unprivileged:1.27-alpine
    environment:
      BACKEND_HOSTNAME: ${BACKEND_HOSTNAME:-api.datenportal.localhost}
      GUI_HOSTNAME:    ${GUI_HOSTNAME:-datenportal.localhost} 
      KEYCLOAK_HOSTNAME: ${KEYCLOAK_HOSTNAME:-auth.datenportal.localhost}
    ports:
      - 443:8443
    volumes:
      - ${FEASIBILITY_PORTAL_PROXY_CERTIFICATE_PATH:-../auth/cert.pem}:/etc/nginx/certs/cert.pem
      - ${FEASIBILITY_PORTAL_PROXY_CERTIFICATE_KEY_PATH:-../auth/key.pem}:/etc/nginx/certs/key.pem
      #- ${FEASIBILITY_PORTAL_PROXY_NGINX_CONFIG:-./context-paths.nginx.conf}:/etc/nginx/nginx.conf:ro     
      - ${FEASIBILITY_PORTAL_PROXY_NGINX_CONFIG:-./subdomains.nginx.conf}:/etc/nginx/nginx.conf:ro     
      - ./conf.d:/etc/nginx/templates:ro


